language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

php:
  - 7.1
  - 7.2

before_install:
  - phpenv config-rm xdebug.ini
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
 - ./vendor/bin/simple-phpunit
 - composer phpstan

jobs:
  include:
    - stage: Linters
      script:
        - ./vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`
        - ./bin/console lint:yaml app/config
        - ./bin/console lint:twig app/Resources
    - stage: Security Checks
      script: ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock

stages:
  - Linters
  - Security Checks

notifications:
  email: false
