imports:
    - { resource: services.yml }

parameters:
    # The token needs to have admin rights on loveOSS organisation
    # for testing purposes
    repository_username: 'loveOSS'
    repository_name: 'test'

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: 1025
    mailer_user: null
    mailer_password: null

    github_token: 'totalyFakeTokenForTests'
    github_secured_token: 'totalyFakeTokenForTests'

    # list of recipients for mail notifications
    recipients:
        'waiting for code review':
            - waiting_code_review@prestashop.com
        'waiting for QA feedback':
            - foo@prestashop.com
            - bar@prestashop.com
            - baz@prestashop.com
        'waiting for PM feedback':
            - waiting_for_pm@prestashop.com

services:

    # Integration tests shouldn't post comments to github
    Psr\Log\NullLogger:

    Tests\AppBundle\Comments\FakeCommentApi:
        - '@Github\Api\Issue\Comments'
        - '%repository_username%'
        - '%repository_name%'
        - '@twig'

    Tests\AppBundle\Commits\FakeRepository:

    Tests\AppBundle\Issues\NullStatusApi:
        arguments:
            - '@AppBundle\Issues\CachedLabelsApi'
            - '%repository_username%'
            - '%repository_name%'

    # Your integrations tests shouldn't post comments to github
    AppBundle\PullRequests\Listener:
        arguments:
            - '@Tests\AppBundle\Comments\FakeCommentApi'
            - '@Tests\AppBundle\Commits\FakeRepository'
            - '@validator'
            - '@AppBundle\PullRequests\Repository'
            - '@Psr\Log\NullLogger'

    AppBundle\Issues\Listener:
        arguments:
            - '@Tests\AppBundle\Issues\NullStatusApi'
            - '@Psr\Log\NullLogger'
