services:
    app.webhook_resolver:
        class: Lpdigital\Github\Parser\WebhookResolver

# GitHub Client
    app.github.client.cache:
        class: Github\HttpClient\CachedHttpClient
        arguments: 
            - 'cache_dir': '%kernel.cache_dir%/github-api/'

    app.github.client:
        class: Github\Client
        arguments: ['@app.github.client.cache']
        calls:
            - ['authenticate', ['http_token', '%github_token%']]

# GitHub API

    app.github.issues_api:
        class: Github\Api\Issue
        factory: ['@app.github.client', api]
        arguments: [issue]

    app.github.comments_api:
        class: Github\Api\Issue\Comments
        factory: ['@app.github.issues_api', comments]

    app.github.pullrequests_api:
        class: Github\Api\PullRequest
        factory: ['@app.github.client', api]
        arguments: [pull_request]

    app.github.repositories_api:
        class: Github\Api\Repo
        factory: ['@app.github.client', api]
        arguments: [repository]

    app.github.organizations_api:
        class: Github\Api\Organization
        factory: ['@app.github.client', api]
        arguments: [organization]

    app.github.search_api:
        class: Github\Api\Search
        factory: ['@app.github.client', api]
        arguments: [search]

    app.github.labels_api:
        class: Github\Api\Issue\Labels
        factory: ['@app.github.issues_api', labels]

    app.github.gitdata_api:
        class: Github\Api\GitData
        factory: ['@app.github.client', api]
        arguments: [gitData]

    app.github.commits_api:
        class: Github\Api\GitData\Commits
        factory: ['@app.github.gitdata_api', commits]

# Application GitHub API

    app.github.cached_labels_api:
        class: AppBundle\Issues\CachedLabelsApi
        arguments: ['@app.github.labels_api', '%repository_username%', '%repository_name%']

    app.status_api:
        class: AppBundle\Issues\StatusApi
        arguments: ['@app.github.cached_labels_api', '%repository_username%', '%repository_name%']

    app.comment_api:
        class: AppBundle\Comments\CommentApi
        arguments:
            - '@app.github.comments_api'
            - '%repository_username%'
            - '%repository_name%'
            - '@twig'

# Listeners (but not Symfony listeners)

    app.issue_listener:
        class: AppBundle\Issues\Listener
        arguments: ['@app.status_api']

    app.pullrequest_listener:
        class: AppBundle\PullRequests\Listener
        arguments:
            - '@app.comment_api'
            - '@validator'
            - '@app.pull_request.repository'
            - '@app.commit.repository'

# Event subscribers

    app.pullrequest_subscriber:
        class: AppBundle\EventSubscriber\PullRequestSubscriber
        calls: 
            - ['setContainer', ['@service_container']]
        tags:
            - { name: kernel.event_subscriber }

    app.issuecomment_subscriber:
        class: AppBundle\EventSubscriber\IssueCommentSubscriber
        calls: 
            - ['setContainer', ['@service_container']]
        tags:
            - { name: kernel.event_subscriber }

    app.issues_subscriber:
        class: AppBundle\EventSubscriber\IssueSubscriber
        calls: 
            - ['setContainer', ['@service_container']]
        tags:
            - { name: kernel.event_subscriber }

# Repositories

    app.pull_request.repository:
        class: AppBundle\PullRequests\Repository
        arguments: 
            - '@app.search.repository'
            - '@app.github.comments_api'
            - '%repository_username%'
            - '%repository_name%'
    
    app.repository_repository:
        class: AppBundle\Repositories\Repository
        arguments:
            - '@app.github.repositories_api'
            - '%repository_username%'
            - '%repository_name%'
    
    app.organization_repository:
        class: AppBundle\Organizations\Repository
        arguments:
            - '@app.github.organizations_api'
            - '%repository_username%'

    app.search.repository:
        class: AppBundle\Search\Repository
        arguments: ['@app.github.search_api', '%repository_username%', '%repository_name%']

    app.commit.repository:
        class: AppBundle\Commits\Repository
        arguments:
            - '@app.github.commits_api'
            - '@app.github.pullrequests_api'
            - '%repository_username%'
            - '%repository_name%'

# Reporters

    app.pull_requests.reporter:
        class: AppBundle\PullRequests\Reporter
        arguments: ['@app.pull_request.repository']

    app.teams.reporter:
        class: AppBundle\Teams\Reporter
        arguments: ['@app.organization_repository']

# Common services
    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ['@mailer', '@twig']
