imports:
    - { resource: services.yml }
    
parameters:
    # the token needs to have admin rights on loveOSS organisation
    # for testing purposes
    repository_username: 'loveOSS'
    repository_name: 'test'

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: 1025
    mailer_user: null
    mailer_password: null
    
services:
    fake_comment_api:
        class: Tests\AppBundle\Comments\FakeCommentApi
        arguments:
            - '@app.github.comments_api'
            - '%repository_username%'
            - '%repository_name%'
            - '@twig'
    app.status_api:
        class: Tests\AppBundle\Issues\NullStatusApi
        arguments: ['@app.github.cached_labels_api', '%repository_username%', '%repository_name%']
    # Your integrations tests shouldn't post comments to github
    app.pullrequest_listener:
        class: AppBundle\PullRequests\Listener
        arguments:
            - '@fake_comment_api'
            - '@app.commit.repository'
            - '@validator'
            - '@app.pull_request.repository'
            - '@logger'